### ISSUE TITLE
Investigating curvature-dependent clustering algorithm

### ISSUE THREAD

**Issue by CMUBOB97** [nlitz88/workzone#12]
For points/cones that are sparse, use curvature to associate them into occupied zones.

Could use nearest neighbors/k-means, also need to come up with a curvature-dependent heuristic.

**Comment by nlitz88** [comment]
Also, real quick: I had a thought earlier today that I thought might be worth sharing.

Maybe for the task of associating/grouping nearby 2D construction objects, maybe something like the Hungarian algorithm could be applied. I think it's typically used for object tracking--but maybe it could work here? Take this with a grain of salt--just a random thought.

**Comment by nlitz88** [comment]
Ended up using morphological closing, and that gave us pretty decent results. May revisit this later, but abandoning for now.
