### ISSUE TITLE
Complete project scope document

### ISSUE THREAD

**Issue by nlitz88** [nlitz88/workzone#3]
Project Scope Document
The recommended outline for the project scope document is as follows:

Cover Page with Project Title and Group Members
Project Summary
Project Motivation
Project Goals
Use Cases
Methodology
What are your inputs, outputs and intermediate processing steps?
How will you tackle this problem? What is your proposed solution?
System Design – include block diagrams, subsystems and components
Demonstration Sequences (from the simplest to the most complex)
Final Demonstration
Intermediate Demonstration (a subset of the Final Demo)
Development Milestones
What will be accomplished by the Intermediate Demo and the Final Demo?
Make this schedule fine-grained to guide your own project development process.
Work Partitioning
How will you partition the work among team-members?
Conclusions
References
Include a few relevant pieces of work available in the literature – ideally, these references are cited in the rest of the document.
Submission:   Please submit your project scope document by email to [rajkumar@cmu.edu](mailto:rajkumar@cmu.edu) and [shrutib@andrew.cmu.edu](mailto:shrutib@andrew.cmu.edu)

**Comment by CMUBOB97** [comment]
Sorry forgot to share: https://docs.google.com/document/d/1myITlUZhzs5H4FrAvcsyeSvQtAiFV63-muI_6SN2br0/edit?usp=sharing
