### ISSUE TITLE
Prepare slides for in-class presentation

### ISSUE THREAD

**Issue by nlitz88** [nlitz88/workzone#5]
Outline of the Initial Project Presentation

The initial project presentation can follow a roughly similar format as the project scope document (as listed in the previous announcement).  However, it is an in-class presentation in front of a live audience.   Hence, it  needs to be much more visual.

Use lots of figures - and make them colorful and appealing.

Use animation where appropriate.  Do not overuse animation, but it can present concepts coherently in an otherwise-visually cluttered slidescape). 

Make your use cases very clear.   And present them from the simplest to the most complex.

List your anticipated demo sequences for the intermediate and final demos, as discussed during the finalization of your project scope.

Time duration:  ~20 minutes for each group (~5-6 minutes for each project member + 5 minutes for Q&A from the entire class + transition time between projects).

We have a good set of projects in store.     

IMPORTANT:  You MUST send your project presentations to me ([rajkumar@cmu.edu](mailto:rajkumar@cmu.edu)) before 3pm on the day of your presentation.   All presentations will be made from my laptop in class to avoid technical glitches with the presentation equipment.  Powerpoint, pdf and Google Slides can be used.

Looking forward to your presentations and the scope documents next week.

- Raj

**Comment by nlitz88** [comment]
@CMUBOB97 @brendaju Created new presentation file specifically for the initial presentation: https://docs.google.com/presentation/d/1lijP_kW2tLj7DO7c5ziHmDeZXeFmtBXgz_LGHCKLkMk/edit?usp=sharing

@CMUBOB97 I will continue work in this file, but we have the progress you made so far.

**Comment by nlitz88** [comment]
Just added slides that follow the outline into the slides. Admittedly, some of these are bit redundant--but definitely a good starting point. I'll try to continue working on these later this evening.

**Comment by nlitz88** [comment]
I'm a little stuck on the summary slide: Should we instead treat it as an outline of sorts? Or should we just try to keep it to a concise overview of what the big idea is? Does that fit?

**Comment by nlitz88** [comment]
@CMUBOB97 @brendaju Okay, I just went through and added figures and visuals for the main talking points. We can work through dividing up the presentation tomorrow and ironing out some of the details.

**Comment by CMUBOB97** [comment]
For summary slides I am splitting it into bullet points to just relate to main things we want to cover in our presentation. Should be good just to stay as what it is now, like an abstract
